$axure.loadCurrentPage({
  "url":"头像.html",
  "generationDate":new Date(1410708706516.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"mouseX",
"mouseY",
"drag",
"number"],
  "page":{
    "packageId":"7699e6c2f6c94a7698746017e2cacd1a",
    "type":"Axure:Page",
    "name":"头像",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 x,<br>x,<br>取消",
                "objectsToFades":[{
                    "objectPath":["77fccf34528446cfbb6966426967542a"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["7d7abda367bc493b8afbe29c37eeab56"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["ce790841e49b40cf994168f205b26d43"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"39ceb16326394bd6a46cf15ca38d671d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":50}},
          "adaptiveStyles":{
},
          "masterId":"dc48e400b7474dc59356ab65988cb125"},
{
          "id":"87967c376b7b43cc8d331e99280cafd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":532,
              "y":309},
            "size":{
              "width":35,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f77ae08df51f409fbb72be3a027917f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":532,
                  "y":309},
                "size":{
                  "width":35,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头像/u5.png"}},
{
          "id":"399db43eaba642178f2771e7b6c5b1ab",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":425,
              "y":321},
            "size":{
              "width":250,
              "height":128},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb440b1415146349e79d9f85fdc723c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":425,
                  "y":321},
                "size":{
                  "width":250,
                  "height":128},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头像/u7.png"}},
{
          "id":"2bc075dc16c7442787e1a2396df52051",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":438,
              "y":338},
            "size":{
              "width":225,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cefeef6cf0146b495973b0ae75be7aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":438,
                  "y":338},
                "size":{
                  "width":225,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头像/u9.png"}},
{
          "id":"381fcb6d459543b690bec039dfb433e9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":500,
              "y":180},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc34ab346364d3e95e6148c404c81ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":500,
                  "y":180},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头像/u11.png",
            "mouseDown~":"images/头像/u11_mouseDown.png"}},
{
          "id":"08b76e50b81b4ee2b067963d60fec38f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":512,
              "y":202},
            "size":{
              "width":75,
              "height":57},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"600e6e6327024ce2a484501267b452f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":512,
                  "y":202},
                "size":{
                  "width":75,
                  "height":57},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 x,<br>x,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["77fccf34528446cfbb6966426967542a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7d7abda367bc493b8afbe29c37eeab56"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ce790841e49b40cf994168f205b26d43"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/头像/u13.png"}},
{
          "id":"7eef60c8aa1d4349ba96a88def3621e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":624,
              "y":427},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4a5859a6ca64e82aa34c49b81ab2914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":427},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的单据",
                      "target":{
                        "targetType":"page",
                        "url":"我的单据.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77fccf34528446cfbb6966426967542a",
          "label":"x",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":400,
              "y":475},
            "size":{
              "width":300,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bcd78a1da484c5d91a6f05b90101e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":400,
                  "y":475},
                "size":{
                  "width":300,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选取",
                      "target":{
                        "targetType":"page",
                        "url":"选取.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/头像/x_u17.png"}},
{
          "id":"7d7abda367bc493b8afbe29c37eeab56",
          "label":"x",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":400,
              "y":511},
            "size":{
              "width":300,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760ebf1535b741079becb443d1fa8d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":400,
                  "y":511},
                "size":{
                  "width":300,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选取",
                      "target":{
                        "targetType":"page",
                        "url":"选取.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/头像/x_u17.png"}},
{
          "id":"ce790841e49b40cf994168f205b26d43",
          "label":"取消",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":400,
              "y":547},
            "size":{
              "width":300,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9e41302a6194217ac2ad3299bbcabd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":400,
                  "y":547},
                "size":{
                  "width":300,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 x,<br>x,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["77fccf34528446cfbb6966426967542a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7d7abda367bc493b8afbe29c37eeab56"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ce790841e49b40cf994168f205b26d43"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/头像/x_u17.png",
            "mouseDown~":"images/头像/取消_u21_mouseDown.png"}}]}},
  "masters":{
    "dc48e400b7474dc59356ab65988cb125":{
      "packageId":"dc48e400b7474dc59356ab65988cb125",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8504578c24f14a8184ebf2c33a781807",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":400,
                "y":50},
              "size":{
                "width":300,
                "height":533}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"d95632e50cf34bc7a4a84787d607d8ad",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"4eb22f7571184d4bab6608115e048c14",
                    "label":"",
                    "parentDynamicPanel":"8504578c24f14a8184ebf2c33a781807",
                    "panelIndex":0,
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":300,
                        "height":533}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":true,
                    "propagate":false,
                    "diagrams":[{
                        "id":"22b08b7010bd4469bc816f3d09acfcaa",
                        "label":"状态1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"c4ef72fe76d544d2883990933f53d373",
                            "label":"",
                            "parentDynamicPanel":"4eb22f7571184d4bab6608115e048c14",
                            "panelIndex":0,
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF37C8AB},
                              "size":{
                                "width":300,
                                "height":533},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b4da05b8ffe24b9f8fbd120919ef033a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"4eb22f7571184d4bab6608115e048c14",
                                "panelIndex":0,
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fill":{
                                    "fillType":"solid",
                                    "color":0xFF37C8AB},
                                  "size":{
                                    "width":300,
                                    "height":533},
                                  "borderFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFF}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/登录/u3.png"}}],
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "image":null,
                          "imageHorizontalAlignment":"near",
                          "imageVerticalAlignment":"near",
                          "imageRepeat":"auto"},
                        "adaptiveStyles":{
}}]}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "39ceb16326394bd6a46cf15ca38d671d":{
      "scriptId":"u0",
      "8504578c24f14a8184ebf2c33a781807":{
        "scriptId":"u1"},
      "4eb22f7571184d4bab6608115e048c14":{
        "scriptId":"u2"},
      "c4ef72fe76d544d2883990933f53d373":{
        "scriptId":"u3"},
      "b4da05b8ffe24b9f8fbd120919ef033a":{
        "scriptId":"u4"}},
    "87967c376b7b43cc8d331e99280cafd7":{
      "scriptId":"u5"},
    "f77ae08df51f409fbb72be3a027917f7":{
      "scriptId":"u6"},
    "399db43eaba642178f2771e7b6c5b1ab":{
      "scriptId":"u7"},
    "4fb440b1415146349e79d9f85fdc723c":{
      "scriptId":"u8"},
    "2bc075dc16c7442787e1a2396df52051":{
      "scriptId":"u9"},
    "4cefeef6cf0146b495973b0ae75be7aa":{
      "scriptId":"u10"},
    "381fcb6d459543b690bec039dfb433e9":{
      "scriptId":"u11"},
    "1fc34ab346364d3e95e6148c404c81ef":{
      "scriptId":"u12"},
    "08b76e50b81b4ee2b067963d60fec38f":{
      "scriptId":"u13"},
    "600e6e6327024ce2a484501267b452f6":{
      "scriptId":"u14"},
    "7eef60c8aa1d4349ba96a88def3621e4":{
      "scriptId":"u15"},
    "e4a5859a6ca64e82aa34c49b81ab2914":{
      "scriptId":"u16"},
    "77fccf34528446cfbb6966426967542a":{
      "scriptId":"u17"},
    "1bcd78a1da484c5d91a6f05b90101e3e":{
      "scriptId":"u18"},
    "7d7abda367bc493b8afbe29c37eeab56":{
      "scriptId":"u19"},
    "760ebf1535b741079becb443d1fa8d34":{
      "scriptId":"u20"},
    "ce790841e49b40cf994168f205b26d43":{
      "scriptId":"u21"},
    "e9e41302a6194217ac2ad3299bbcabd3":{
      "scriptId":"u22"}}});