$axure.loadCurrentPage({
  "url":"new_page_1.html",
  "generationDate":new Date(1410945750058.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"number",
"movepanel",
"upown"],
  "page":{
    "packageId":"4383454ee4a94afe86c5bb18c739297c",
    "type":"Axure:Page",
    "name":"New Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1720ad27e48c4aa9b190d855de345e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":98},
            "size":{
              "width":630,
              "height":422},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3846789cede4b59b18a180d4e21efc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":98},
                "size":{
                  "width":630,
                  "height":422},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u0.png"}},
{
          "id":"9b1b729d4a734e2ea9b7bc914a19abd1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":167},
            "size":{
              "width":512,
              "height":377}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b1280e76e034cf0b2414965086857e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":167},
                "size":{
                  "width":512,
                  "height":377}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u2.png"}},
{
          "id":"5502f14a94f2427da5caad593940a5c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF64BED5},
            "location":{
              "x":160,
              "y":99},
            "size":{
              "width":630,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2e7774fd79c457d9d8b13717cee143d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF64BED5},
                "location":{
                  "x":160,
                  "y":99},
                "size":{
                  "width":630,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u4.png"}},
{
          "id":"e1d653e18f1c47f58c33744eee3f68c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F0F0},
            "location":{
              "x":160,
              "y":130},
            "size":{
              "width":630,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229cce3445cf4b3db7fa962873bbd693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F0F0},
                "location":{
                  "x":160,
                  "y":130},
                "size":{
                  "width":630,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u6.png"}},
{
          "id":"3229300bc0724335beb7c67dee2ba48d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF278CDE,
              "opacity":1},
            "location":{
              "x":178,
              "y":142},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd354e9056c54083a4fcf6325c4d7aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF278CDE,
                  "opacity":1},
                "location":{
                  "x":178,
                  "y":142},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9045189155441b5bbbeede88291ecbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":268,
              "y":142},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e54af6cb8ded4857a46219520b633a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":268,
                  "y":142},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5a99995c0ad4ffb92d3dc039ce6bd7e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":138},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"69b6a449dc9c41aab4e0e75d60c8aed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEDEEEE},
            "location":{
              "x":160,
              "y":201},
            "size":{
              "width":110,
              "height":343},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e5288b7194644c88e07fbeb647b0058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEDEEEE},
                "location":{
                  "x":160,
                  "y":201},
                "size":{
                  "width":110,
                  "height":343},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u13.png"}},
{
          "id":"a32ad40b537d479d9ab313b10d8e81da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":180},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d47bb8b60e43ac9a668bba8998cc67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":180},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c535e434aad4ad68812046016899825",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":215},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9adcfa70204e46d7b10da92590f408bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":215},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a96f409f35cd481c8d452a1da4eeaa23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":250},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f21909328ebc40ac970cf8ad016a65a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":250},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab03f3f0b72948c68a9275abc0c1aff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":284},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a839bcc6ba64b36b076ac78b9e1c31d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":284},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9d9aa6ecd92485aba703da78f65f312",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6FB64C},
            "location":{
              "x":453,
              "y":364},
            "size":{
              "width":14,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb0a0ffb3e84a1788f901078418f75a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6FB64C},
                "location":{
                  "x":453,
                  "y":364},
                "size":{
                  "width":14,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u23.png"}},
{
          "id":"f4b91c22ee744cc4a615cd4c0bd44224",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6FB64C,
              "opacity":1},
            "location":{
              "x":475,
              "y":363},
            "size":{
              "width":63,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d798b04c82de4b38886047dccbd6cb5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6FB64C,
                  "opacity":1},
                "location":{
                  "x":475,
                  "y":363},
                "size":{
                  "width":63,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1720ad27e48c4aa9b190d855de345e97":{
      "scriptId":"u0"},
    "e3846789cede4b59b18a180d4e21efc0":{
      "scriptId":"u1"},
    "9b1b729d4a734e2ea9b7bc914a19abd1":{
      "scriptId":"u2"},
    "9b1280e76e034cf0b2414965086857e2":{
      "scriptId":"u3"},
    "5502f14a94f2427da5caad593940a5c1":{
      "scriptId":"u4"},
    "c2e7774fd79c457d9d8b13717cee143d":{
      "scriptId":"u5"},
    "e1d653e18f1c47f58c33744eee3f68c4":{
      "scriptId":"u6"},
    "229cce3445cf4b3db7fa962873bbd693":{
      "scriptId":"u7"},
    "3229300bc0724335beb7c67dee2ba48d":{
      "scriptId":"u8"},
    "dd354e9056c54083a4fcf6325c4d7aba":{
      "scriptId":"u9"},
    "e9045189155441b5bbbeede88291ecbc":{
      "scriptId":"u10"},
    "e54af6cb8ded4857a46219520b633a07":{
      "scriptId":"u11"},
    "e5a99995c0ad4ffb92d3dc039ce6bd7e":{
      "scriptId":"u12"},
    "69b6a449dc9c41aab4e0e75d60c8aed9":{
      "scriptId":"u13"},
    "5e5288b7194644c88e07fbeb647b0058":{
      "scriptId":"u14"},
    "a32ad40b537d479d9ab313b10d8e81da":{
      "scriptId":"u15"},
    "a0d47bb8b60e43ac9a668bba8998cc67":{
      "scriptId":"u16"},
    "1c535e434aad4ad68812046016899825":{
      "scriptId":"u17"},
    "9adcfa70204e46d7b10da92590f408bd":{
      "scriptId":"u18"},
    "a96f409f35cd481c8d452a1da4eeaa23":{
      "scriptId":"u19"},
    "f21909328ebc40ac970cf8ad016a65a8":{
      "scriptId":"u20"},
    "ab03f3f0b72948c68a9275abc0c1aff5":{
      "scriptId":"u21"},
    "4a839bcc6ba64b36b076ac78b9e1c31d":{
      "scriptId":"u22"},
    "a9d9aa6ecd92485aba703da78f65f312":{
      "scriptId":"u23"},
    "ccb0a0ffb3e84a1788f901078418f75a":{
      "scriptId":"u24"},
    "f4b91c22ee744cc4a615cd4c0bd44224":{
      "scriptId":"u25"},
    "d798b04c82de4b38886047dccbd6cb5f":{
      "scriptId":"u26"}}});