$axure.loadCurrentPage({
  "url":"home的副本_1.html",
  "generationDate":new Date(1411310751681.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f281475625f344fa8b7c94730b168d74",
    "type":"Axure:Page",
    "name":"Home的副本",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"设置 选中状态值 我，田沁园 = &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["630a81faaaea4227b638eb5a003bafab"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}},
{
                "action":"setFunction",
                "description":"设置 选中状态值 一点点经历 = &quot;false&quot;, 且<br> 选中状态值 项目经验 = &quot;false&quot;, 且<br> 选中状态值 软硬技能 = &quot;false&quot;, 且<br> 选中状态值 联系我 = &quot;false&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["abe05b276a004e6d95fc501784cf23a0"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["f16ccfb11c184462a4fbbc03e0d0e999"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["dc79f2cd6c43498a918caa92e371cefb"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["996e36cb1f23435d951361ff65c58520"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]}]}},
{
                "action":"setFunction",
                "description":"设置 变量 OnLoadVariable = &quot;0&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"OnLoadVariable"},
{
                          "exprType":"stringLiteral",
                          "value":"0",
                          "stos":[]}]}]}},
{
                "action":"fadeWidget",
                "description":"显示/隐藏部件",
                "objectsToFades":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"360cc9a742c54f8fbb1d637c862688e2",
          "label":"背景",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":-160},
            "size":{
              "width":1600,
              "height":1066}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"926b6daaa3244dd18bef4d69f28a5c99",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3fd441022b5c454cb9cc1bfd9c457906",
                  "label":"图片",
                  "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xB2FFFFFF,
                      "opacity":0.69803923368454},
                    "size":{
                      "width":1600,
                      "height":1066}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a86613b404fa44f1a6a4e7dc9659c4f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xB2FFFFFF,
                          "opacity":0.69803923368454},
                        "size":{
                          "width":1600,
                          "height":1066}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_1/图片_u1.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c8a75e83c4b84b32a46daf105d631fcf",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b31c6c02d7ff4dbab9906cab80ba2985",
                  "label":"",
                  "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1600,
                      "height":1066}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad2757eb4b57414c9b41b4e4c68545c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1600,
                          "height":1066}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_1/u3.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"df4cf06fd61c4503ac11b514596da4ed",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4058a5a12e9240e6995533654719dda4",
                  "label":"",
                  "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":228},
                    "size":{
                      "width":1600,
                      "height":1066}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"355f0e9c52da4c53b4a1b73fcd87bfbc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":228},
                        "size":{
                          "width":1600,
                          "height":1066}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_1/u5.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"59ebb2394aad48f481bceee50166785d",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f441cbf6384449bca700346200c7e407",
                  "label":"",
                  "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1600,
                      "height":1066}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ffd33be26ee424a86cc73a119140ebe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"360cc9a742c54f8fbb1d637c862688e2",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1600,
                          "height":1066}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_1/u7.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"7cbfb8ae060a420482197a27cacc3f9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7FFFFFFF},
            "location":{
              "x":301,
              "y":460},
            "size":{
              "width":1470,
              "height":450},
            "borderFill":{
              "fillType":"solid",
              "color":0x1CFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8585a197344e76bb70e23694c746d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF},
                "location":{
                  "x":301,
                  "y":460},
                "size":{
                  "width":1470,
                  "height":450},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home的副本_1/u9.png"}},
{
          "id":"630a81faaaea4227b638eb5a003bafab",
          "label":"我，田沁园",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929},
                "fill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":461},
            "size":{
              "width":142,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab1552a54c2409996528a2eb8cbd544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929},
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x1CFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":461},
                "size":{
                  "width":142,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"images/home的副本_1/我，田沁园_u11_selected.png",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"abe05b276a004e6d95fc501784cf23a0",
          "label":"一点点经历",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929},
                "fill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":549},
            "size":{
              "width":142,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b95d56ed3584013826650c21bdb1443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929},
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x1CFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":549},
                "size":{
                  "width":142,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"images/home的副本_1/我，田沁园_u11_selected.png",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f16ccfb11c184462a4fbbc03e0d0e999",
          "label":"项目经验",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929},
                "fill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":637},
            "size":{
              "width":142,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b03140407b401182ca45e48f94c923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929},
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x1CFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":637},
                "size":{
                  "width":142,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"images/home的副本_1/我，田沁园_u11_selected.png",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"dc79f2cd6c43498a918caa92e371cefb",
          "label":"软硬技能",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929},
                "fill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":725},
            "size":{
              "width":142,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"030185ef456e4af4bf1d3e29803b04e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929},
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x1CFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":725},
                "size":{
                  "width":142,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"images/home的副本_1/我，田沁园_u11_selected.png",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"996e36cb1f23435d951361ff65c58520",
          "label":"联系我",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xCC000000,
                  "opacity":0.800000011920929},
                "fill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x1CFFFFFF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":160,
              "y":813},
            "size":{
              "width":142,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386e7d5544c74e76a241c7971674ff00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xCC000000,
                      "opacity":0.800000011920929},
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FFFFFFF},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x1CFFFFFF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":160,
                  "y":813},
                "size":{
                  "width":142,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"images/home的副本_1/我，田沁园_u11_selected.png",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "360cc9a742c54f8fbb1d637c862688e2":{
      "scriptId":"u0"},
    "3fd441022b5c454cb9cc1bfd9c457906":{
      "scriptId":"u1"},
    "a86613b404fa44f1a6a4e7dc9659c4f7":{
      "scriptId":"u2"},
    "b31c6c02d7ff4dbab9906cab80ba2985":{
      "scriptId":"u3"},
    "ad2757eb4b57414c9b41b4e4c68545c1":{
      "scriptId":"u4"},
    "4058a5a12e9240e6995533654719dda4":{
      "scriptId":"u5"},
    "355f0e9c52da4c53b4a1b73fcd87bfbc":{
      "scriptId":"u6"},
    "f441cbf6384449bca700346200c7e407":{
      "scriptId":"u7"},
    "2ffd33be26ee424a86cc73a119140ebe":{
      "scriptId":"u8"},
    "7cbfb8ae060a420482197a27cacc3f9d":{
      "scriptId":"u9"},
    "4e8585a197344e76bb70e23694c746d6":{
      "scriptId":"u10"},
    "630a81faaaea4227b638eb5a003bafab":{
      "scriptId":"u11"},
    "0ab1552a54c2409996528a2eb8cbd544":{
      "scriptId":"u12"},
    "abe05b276a004e6d95fc501784cf23a0":{
      "scriptId":"u13"},
    "3b95d56ed3584013826650c21bdb1443":{
      "scriptId":"u14"},
    "f16ccfb11c184462a4fbbc03e0d0e999":{
      "scriptId":"u15"},
    "44b03140407b401182ca45e48f94c923":{
      "scriptId":"u16"},
    "dc79f2cd6c43498a918caa92e371cefb":{
      "scriptId":"u17"},
    "030185ef456e4af4bf1d3e29803b04e3":{
      "scriptId":"u18"},
    "996e36cb1f23435d951361ff65c58520":{
      "scriptId":"u19"},
    "386e7d5544c74e76a241c7971674ff00":{
      "scriptId":"u20"}}});