$axure.loadCurrentPage({
  "url":"home的副本_2.html",
  "generationDate":new Date(1411310752024.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5c80fa27e3c44a92a9b68843aaaf8ae5",
    "type":"Axure:Page",
    "name":"Home的副本",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"设置 选中状态值 我，田沁园 = &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["630a81faaaea4227b638eb5a003bafab"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}},
{
                "action":"setFunction",
                "description":"设置 选中状态值 一点点经历 = &quot;false&quot;, 且<br> 选中状态值 项目经验 = &quot;false&quot;, 且<br> 选中状态值 软硬技能 = &quot;false&quot;, 且<br> 选中状态值 联系我 = &quot;false&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["abe05b276a004e6d95fc501784cf23a0"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["f16ccfb11c184462a4fbbc03e0d0e999"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["dc79f2cd6c43498a918caa92e371cefb"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["996e36cb1f23435d951361ff65c58520"]},
{
                          "exprType":"stringLiteral",
                          "value":"false",
                          "stos":[]}]}]}},
{
                "action":"fadeWidget",
                "description":"隐藏 wo ",
                "objectsToFades":[{
                    "objectPath":["01125e9f036b4290a521cb5f073e38f1"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]},
      "onScroll":{
        "description":"OnScroll",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 图片 向上滑动 500 毫秒 收起 部件 向下 线性 500ms",
                "objectsToFades":[{
                    "objectPath":["6ef8a89984ee491d88239759868088fd"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "easing":"slideUp",
                        "duration":500,
                        "showType":"compress",
                        "vertical":true,
                        "compressEasing":"linear",
                        "compressDuration":500}}}]},
{
                "action":"fadeWidget",
                "description":"显示 wo 展开 部件 向下 线性 500ms",
                "objectsToFades":[{
                    "objectPath":["01125e9f036b4290a521cb5f073e38f1"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"compress",
                        "vertical":true,
                        "compressEasing":"linear",
                        "compressDuration":500}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"ca1d8066f3e74533908bb58693c8c530",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":2590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a64951fdc04e8e8fe3ea58e0068b1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":2590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home的副本_2/u0.png"}},
{
          "id":"01125e9f036b4290a521cb5f073e38f1",
          "label":"wo ",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1090dcc563024742849c4cb00a382cc9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"6ef8a89984ee491d88239759868088fd",
          "label":"图片",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xB2FFFFFF,
              "opacity":0.69803923368454},
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a9ae3fd593749fb89ffadd701e587fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xB2FFFFFF,
                  "opacity":0.69803923368454},
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home的副本_2/图片_u3.jpg"}},
{
          "id":"b28e925ecd7c4ffd881334e4dd607390",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"67c7190601594340a6c1cec08f205e45",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"866fdc78a4e540369ece83474aec5c07",
                  "label":"",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "location":{
                      "x":1110,
                      "y":0},
                    "size":{
                      "width":490,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b69bee6c62e94176a7953d5152f4107e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "location":{
                          "x":1110,
                          "y":0},
                        "size":{
                          "width":490,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/u6.png"}},
{
                  "id":"630a81faaaea4227b638eb5a003bafab",
                  "label":"我，田沁园",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6384BA,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929}},
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "location":{
                      "x":420.000061035156,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ab1552a54c2409996528a2eb8cbd544",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6384BA,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929}},
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "location":{
                          "x":420.000061035156,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/我，田沁园_u8.png",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"images/home的副本_2/我，田沁园_u8.png"}},
{
                  "id":"abe05b276a004e6d95fc501784cf23a0",
                  "label":"一点点经历",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6384BA,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929}},
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "location":{
                      "x":558.000061035156,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b95d56ed3584013826650c21bdb1443",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6384BA,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929}},
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "location":{
                          "x":558.000061035156,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/我，田沁园_u8.png",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"images/home的副本_2/我，田沁园_u8.png"}},
{
                  "id":"f16ccfb11c184462a4fbbc03e0d0e999",
                  "label":"项目经验",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6384BA,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929}},
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "location":{
                      "x":696.000061035156,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44b03140407b401182ca45e48f94c923",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6384BA,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929}},
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "location":{
                          "x":696.000061035156,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/我，田沁园_u8.png",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"images/home的副本_2/我，田沁园_u8.png"}},
{
                  "id":"dc79f2cd6c43498a918caa92e371cefb",
                  "label":"软硬技能",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6384BA,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929}},
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "location":{
                      "x":834.000061035156,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"030185ef456e4af4bf1d3e29803b04e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6384BA,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929}},
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "location":{
                          "x":834.000061035156,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/我，田沁园_u8.png",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"images/home的副本_2/我，田沁园_u8.png"}},
{
                  "id":"996e36cb1f23435d951361ff65c58520",
                  "label":"联系我",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6384BA,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929}},
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xCC333333,
                          "opacity":0.800000011920929},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "location":{
                      "x":972.000061035156,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"386e7d5544c74e76a241c7971674ff00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6384BA,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929}},
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xCC333333,
                              "opacity":0.800000011920929},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "location":{
                          "x":972.000061035156,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/我，田沁园_u8.png",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"images/home的副本_2/我，田沁园_u8.png"}},
{
                  "id":"258a693d069a462c8c2cef1ccc1d963d",
                  "label":"",
                  "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x99FFFFFF},
                    "size":{
                      "width":422,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f60e6b508533460dbb31cedf0e3eb272",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b28e925ecd7c4ffd881334e4dd607390",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x99FFFFFF},
                        "size":{
                          "width":422,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home的副本_2/u18.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "ca1d8066f3e74533908bb58693c8c530":{
      "scriptId":"u0"},
    "90a64951fdc04e8e8fe3ea58e0068b1c":{
      "scriptId":"u1"},
    "01125e9f036b4290a521cb5f073e38f1":{
      "scriptId":"u2"},
    "6ef8a89984ee491d88239759868088fd":{
      "scriptId":"u3"},
    "6a9ae3fd593749fb89ffadd701e587fd":{
      "scriptId":"u4"},
    "b28e925ecd7c4ffd881334e4dd607390":{
      "scriptId":"u5"},
    "866fdc78a4e540369ece83474aec5c07":{
      "scriptId":"u6"},
    "b69bee6c62e94176a7953d5152f4107e":{
      "scriptId":"u7"},
    "630a81faaaea4227b638eb5a003bafab":{
      "scriptId":"u8"},
    "0ab1552a54c2409996528a2eb8cbd544":{
      "scriptId":"u9"},
    "abe05b276a004e6d95fc501784cf23a0":{
      "scriptId":"u10"},
    "3b95d56ed3584013826650c21bdb1443":{
      "scriptId":"u11"},
    "f16ccfb11c184462a4fbbc03e0d0e999":{
      "scriptId":"u12"},
    "44b03140407b401182ca45e48f94c923":{
      "scriptId":"u13"},
    "dc79f2cd6c43498a918caa92e371cefb":{
      "scriptId":"u14"},
    "030185ef456e4af4bf1d3e29803b04e3":{
      "scriptId":"u15"},
    "996e36cb1f23435d951361ff65c58520":{
      "scriptId":"u16"},
    "386e7d5544c74e76a241c7971674ff00":{
      "scriptId":"u17"},
    "258a693d069a462c8c2cef1ccc1d963d":{
      "scriptId":"u18"},
    "f60e6b508533460dbb31cedf0e3eb272":{
      "scriptId":"u19"}}});